environment:
  matrix:
  - CMAKE_GENERATOR: "Visual Studio 14 2015"
  - CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# scripts to run before build
before_build:
  - echo Running cmake ...
  - cmake -H. -Bbuild -G "%CMAKE_GENERATOR%"

build_script:
  - echo Building ...
  - cmake --build build --config "%CONFIGURATION%"

after_build:
  - ctest -VV

artifacts:
  - path: build/msvsover
